version: '3.7'

services: # the different images that will be running as containers
  web: # service name
    build: . #build the image for the web service from the dockerfile in parent directory.
    volumes:
      - .:/app # map data and files from parent directory in host to plio directory in docker container
    env_file: # file where env variables are stored. Used as best practice so as not to expose secret keys
      - .env # name of the env file
    image: plio-frontend # name of the image
    ports:
      - "${APP_PORT}:80"
    restart: "on-failure"
